Updated dev_cluster setup README to match latest updates
fabric8-analytics/fabric8-analytics-deployment pull request #44
Opened 2019-06-19 05:33 UTC by deepak1725

Added PR Steps and General FAQ's

2019-06-19 13:06 UTC, samuzzal-choudhury requested changes

2019-06-19 13:06 UTC, samuzzal-choudhury commented on openshift/README-AWS_Access.md
> +Next step is to get credentials to signin in your dev AWS Console
**Correction**: Next step is to get credentials to get access to your own AWS console.

2019-06-19 13:06 UTC, samuzzal-choudhury commented on openshift/README-AWS_Access.md
> +2. Open a MR at https://gitlab.cee.redhat.com/dtsd/devguide/blob/master/devguide.md#requesting-access
`Create a Merge Request` instead of `Open a MR`.

2019-06-19 13:06 UTC, samuzzal-choudhury commented on openshift/README-AWS_Access.md
> +3. Repo would likely be forked.
Could not get what this step means

2019-06-19 13:06 UTC, samuzzal-choudhury commented on openshift/README-AWS_Access.md
> +4. Before trying to put a Merge Request, make sure to add `@devtools-bot` with role as **Maintainer** in your forked repo settings.
Replace `trying to put` with `creating`

2019-06-19 13:06 UTC, samuzzal-choudhury commented on openshift/README-AWS_Access.md
> +5. With your new `kerbroseid.yml` file, Put a Merge Request in Base Repo while ensuring that all automated tests are passed.
Replace `Put` with `create`.

2019-06-19 13:06 UTC, samuzzal-choudhury commented on openshift/README-AWS_Access.md
> + Go to [README.md](README.md)
@deepak1725 please take this text through a grammar checker browser extension.

2019-06-19 14:30 UTC, deepak1725 commented on openshift/README-AWS_Access.md
> +3. Repo would likely be forked.
reworded.

2019-06-19 14:31 UTC, deepak1725 commented on openshift/README-AWS_Access.md
> + Go to [README.md](README.md)
Noted

2019-06-23 14:43 UTC, maheshwari-git commented on openshift/README.md
Removal of the below was required for execution,
1. RDS creation in helper.sh
2. --db-subnet-group-name "${RDS_SUBNET_GROUP_NAME}" \

2019-06-23 14:43 UTC, maheshwari-git commented on openshift/README.md
Once the Pod's up need to value the services by triggering API endpoint 
example : Component Analysis
http://<"your-api-endpoint">/api/v1/component-analyses/npm/serve-static/1.7.1
example : Stack Analysis

2019-06-23 14:43 UTC, maheshwari-git commented on openshift/README.md
For validating your stack analysis call, use Postman 

Headers which need to be set are
key : x-3scale-account-secret  value: 
key : Content-Type value: application/x-www-form-urlencoded
key : ecosystem value : <"npm">/<"pyp"i>
key: origin value:vscode

Body
key : manifest[]  value : "pom.xml" / "package.json"
key: filePath[]  value : "some path" -this is not used in the api

2019-06-23 14:43 UTC, maheshwari-git commented on openshift/README.md
For Stack Analysis call ensure your hpf-insights job is running. If it is not then you need to launch the service using the "deploy using yaml file" option on your openshift console.

Pick the yaml file from your cloned repo f8a-hpf-insights/openshift/template.yaml

2019-06-23 14:48 UTC, deepak1725 commented on openshift/README.md
I think i should put a separate PR removing this..
https://github.com/fabric8-analytics/fabric8-analytics-deployment/blob/cc58a9abaaf18b99857f913e9cd42387a3e91ce4/openshift/helpers.sh#L104

2019-07-03 10:13 UTC, samuzzal-choudhury approved these changes
@deepak1725 Thank you for the PR. Please merge this.

2019-07-04 05:49 UTC, merged